all: release

release:
	gcc -o ../bin/client -Werror client.c ./modules/list-all-downloaded/ListAllDownloaded.c ./modules/list-all-downloaded/ListAllDownloaded.h ./modules/list-all-drive-files/ListAllDriveFiles.c ./modules/list-all-drive-files/ListAllDriveFiles.h ./modules/delete/Delete.c ./modules/delete/Delete.h ./modules/authentication-request/AuthenticationRequest.c ./modules/authentication-request/AuthenticationRequest.h ./modules/common/Common.c ./modules/common/Common.h ./modules/download/Download.c ./modules/download/Download.h ./modules/upload/Upload.c ./modules/upload/Upload.h ./modules/user-input/UserInput.c ./modules/user-input/UserInput.h 


